import {Platform, StyleSheet} from 'react-native';
import {color, styles} from '../../../utils/styles';

const stylesCust = StyleSheet.create({
  page: {flex: 1},
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
  },
  buttonClear: {
    width: 45,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
  },
  button: {
    width: 38,
    height: 38,
    backgroundColor: color.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
  },
  buttonContainer: {
    width: 38,
    height: 38,
    right: 13,
    bottom: 120,
    position: 'absolute',
  },
  searchContainer: {
    position: 'absolute',
    top: 30,
    width: '100%',
    minHeight: 50,
    overflow: 'hidden',
    backgroundColor: color.loading,
  },
  buttonModalize: {
    paddingHorizontal: 30,
    paddingVertical: 10,
    justifyContent: 'space-between',
    flexDirection: 'row',
    position: 'absolute',
    width: '100%',
    bottom: 300,
  },
  routeContainer: {
    minHeight: 50,
    backgroundColor: color.white,
    marginHorizontal: 30,
    marginVertical: 20,
    borderRadius: 10,
  },
  routeBody: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  routeTitle: {flex: 1, paddingVertical: 10, paddingRight: 10},
  contentBottom: {
    marginHorizontal: 30,
    paddingVertical: 20,
  },
  content: [
    {
      borderTopRightRadius: 25,
      borderTopLeftRadius: 25,
      backgroundColor: color.white,
      height: 300,
      width: '100%',
      position: 'absolute',
      bottom: 0,
      // paddingHorizontal: 30,
      paddingVertical: 20,
    },
    styles.shadowCust(),
  ],
  selectTransport: {
    paddingHorizontal: 30,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: color.white4,
  },
  imageContainer: {width: 50, marginRight: 20},
  image: {resizeMode: 'contain', width: undefined, height: 50},
  markerFixed: {
    left: '50%',
    marginLeft: -35,
    marginTop: -62,
    position: 'absolute',
    top: '47%',
  },
  marker: {
    resizeMode: 'contain',
    height: 70,
    width: 70,
  },
  markerCust: [
    {
      backgroundColor: color.green3,
      width: 35,
      height: 35,
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 3,
      borderColor: color.white2,
    },
    styles.shadowCust(20),
  ],
  address: backgroundColor => ({
    padding: 20,
    backgroundColor: backgroundColor,
    borderRadius: 10,
    marginBottom: 20,
    marginRight: 30,
    width: 270,
  }),
  locationTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 30,
  },
  iconTransparent: (clr = color.green3) => ({
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    color: clr,
  }),
  iconCust: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationList: {height: 150},
  locationButton: {paddingHorizontal: 30},
});

export default stylesCust;
